version: 2.1

executors:
  node:
    parameters:
      version:
        type: string
        default: lts
    docker:
      - image: circleci/node:<< parameters.version >>
    working_directory: ~/marp-vscode

commands:
  install:
    parameters:
      postinstall:
        type: steps
        default: []
      yarn:
        type: string
        default: 1.19.1
    steps:
      # https://github.com/nodejs/docker-node/blob/master/docs/BestPractices.md#upgradingdowngrading-yarn
      - run:
          name: Upgrade yarn
          command: |
            sudo -E sh -c 'curl -fSLO --compressed "https://yarnpkg.com/downloads/$YARN_VERSION/yarn-v$YARN_VERSION.tar.gz" \
              && tar -xzf yarn-v$YARN_VERSION.tar.gz -C /opt/ \
              && ln -snf /opt/yarn-v$YARN_VERSION/bin/yarn /usr/local/bin/yarn \
              && ln -snf /opt/yarn-v$YARN_VERSION/bin/yarnpkg /usr/local/bin/yarnpkg \
              && rm yarn-v$YARN_VERSION.tar.gz'
          environment:
            YARN_VERSION: << parameters.yarn >>

      - restore_cache:
          keys:
            - v2.1-dependencies-{{ .Environment.CI_CACHE_KEY }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "yarn.lock" }}-{{ .Branch }}
            - v2.1-dependencies-{{ .Environment.CI_CACHE_KEY }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "yarn.lock" }}-
            - v2.1-dependencies-{{ .Environment.CI_CACHE_KEY }}-{{ .Environment.CIRCLE_JOB }}-

      - run: yarn install
      - steps: << parameters.postinstall >>

      - save_cache:
          key: v2.1-dependencies-{{ .Environment.CI_CACHE_KEY }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "yarn.lock" }}-{{ .Branch }}
          paths:
            - node_modules
            - ~/.cache/yarn

  audit:
    steps:
      - checkout
      - install:
          postinstall:
            - run: yarn audit

  test:
    steps:
      - run: node --version

      - checkout
      - install

      - run:
          name: Prettier formatting
          command: yarn check:format

      - run:
          name: TypeScript type checking
          command: yarn check:ts

      - run:
          name: TSLint
          command: yarn lint:ts

      - run:
          name: stylelint
          command: yarn lint:css

      - run:
          name: Jest
          command: yarn test:unit:coverage --ci --maxWorkers=2 --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT_DIR: tmp/test-results

      - run: yarn codecov

      - store_test_results:
          path: tmp/test-results

      - store_artifacts:
          path: ./coverage
          destination: coverage

jobs:
  audit:
    executor: node
    steps:
      - audit

  unit-electron4:
    executor:
      name: node
      version: '10.11.0'
    steps:
      - test

workflows:
  test:
    jobs:
      - audit
      - unit-electron4:
          requires:
            - audit
